# Operaciones sobre ndarrays

NumPy pone a nuestra disposición un amplio conjunto de funciones optimizadas para aplicar sobre ndarrays de forma global evitando así la necesidad de utilizar bucles (mucho más costosos).

In [1]:
import numpy as np

### Operaciones elemento a elemento - Universal functions

El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas "funciones universales" (o ufuncs) que permiten la realización de operaciones elemento a elemento de un array. En función del número de parámetros encontramos dos tipos de funciones universales.

#### Funciones unarias

Son aquellas funciones que reciben como parámetro un único ndarray.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada (equivalente a array \*\* 0.5).</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o no.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a ~(array)).</li>
</ul>

In [2]:
array = np.random.randn(5, 5)
array

array([[ 1.51552132,  0.7589027 , -0.80290275,  0.08398705, -0.52218905],
       [ 1.27512575, -0.24981794, -0.04658834,  1.38871066,  0.40185589],
       [-1.89805764, -0.49713007,  1.11755564, -1.10892116, -1.07309004],
       [ 1.00476709,  0.16885473,  0.04298561,  0.14560754, -0.07028653],
       [ 2.02062601, -0.69254555,  1.2567792 ,  0.31515066,  0.65369793]])

In [3]:
np.abs(array)

array([[1.51552132, 0.7589027 , 0.80290275, 0.08398705, 0.52218905],
       [1.27512575, 0.24981794, 0.04658834, 1.38871066, 0.40185589],
       [1.89805764, 0.49713007, 1.11755564, 1.10892116, 1.07309004],
       [1.00476709, 0.16885473, 0.04298561, 0.14560754, 0.07028653],
       [2.02062601, 0.69254555, 1.2567792 , 0.31515066, 0.65369793]])

In [4]:
np.sign(array)

array([[ 1.,  1., -1.,  1., -1.],
       [ 1., -1., -1.,  1.,  1.],
       [-1., -1.,  1., -1., -1.],
       [ 1.,  1.,  1.,  1., -1.],
       [ 1., -1.,  1.,  1.,  1.]])

In [5]:
np.ceil(array)

array([[ 2.,  1., -0.,  1., -0.],
       [ 2., -0., -0.,  2.,  1.],
       [-1., -0.,  2., -1., -1.],
       [ 2.,  1.,  1.,  1., -0.],
       [ 3., -0.,  2.,  1.,  1.]])

#### Funciones binarias

Son aquellas funciones que reciben como parámetro dos arrays.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2). #igual que operadores</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>

In [6]:
array1 = np.random.randn(5, 5)
array1

array([[-0.46933048,  0.47374602,  3.13227441, -0.74224894, -1.6892701 ],
       [-1.9359036 ,  0.69865623,  0.91503501, -0.2871225 , -1.1777283 ],
       [ 1.04870597, -1.56838931,  0.78363951, -0.1059788 ,  0.0663117 ],
       [-1.10606206,  1.21635022,  1.5364152 , -1.31126544, -0.14704846],
       [-1.76057924, -0.41286662,  0.57508645,  0.67818811,  0.4463437 ]])

In [7]:
array2 = np.random.randn(5, 5)
array2

array([[-0.77133324, -0.93492251,  0.46073021, -0.00653321,  2.3799413 ],
       [-0.11711194, -0.14532346, -0.47174256,  1.39432655,  0.58489197],
       [ 0.08132892, -0.46831798, -0.76510145,  0.4531682 , -0.08245417],
       [-0.64586657,  1.24452528,  1.40648804, -1.03707964,  0.37235917],
       [-1.04032814, -1.76230097, -0.63626976,  0.96736799,  0.29885176]])

In [8]:
np.minimum(array1, array2)

array([[-0.77133324, -0.93492251,  0.46073021, -0.74224894, -1.6892701 ],
       [-1.9359036 , -0.14532346, -0.47174256, -0.2871225 , -1.1777283 ],
       [ 0.08132892, -1.56838931, -0.76510145, -0.1059788 , -0.08245417],
       [-1.10606206,  1.21635022,  1.40648804, -1.31126544, -0.14704846],
       [-1.76057924, -1.76230097, -0.63626976,  0.67818811,  0.29885176]])

### Selección de elementos de ndarrays en función de una condición

NumPy pone a nuestra disposición, a través de la función <b>np.where</b> la posibilidad de generar un array de salida a partir de dos de entrada, estableciendo una máscara booleana que indique si (elemento a elemento) debemos enviar a la salida el elemento del primer ndarray (valor True) o del segundo (valor False).

In [9]:
array1 = np.random.randn(5, 5)
array1

array([[ 0.77185237,  0.19639932,  0.39924044,  0.6060406 , -0.47116163],
       [ 0.17025962,  0.84328705,  0.46343659, -0.74515301, -0.08960301],
       [-0.13454219,  0.1129777 , -0.2794793 , -0.29602958, -0.10288192],
       [-1.55343445, -1.59939284,  1.09039858,  0.4333707 ,  1.93677982],
       [ 1.3441032 ,  0.06281218,  1.90645874, -0.25319833, -1.52952003]])

In [10]:
array2 = np.random.randn(5, 5)
array2

array([[ 0.91981524,  0.72951887,  0.37070766,  0.19735883, -0.51541124],
       [-1.33404705,  1.12967337, -1.85125891, -0.29609374,  0.82780325],
       [-0.20238562, -0.92818649,  0.96260877, -1.05604296, -1.10622212],
       [ 0.86106513, -1.86590035,  0.49233096,  0.05255646,  1.23983636],
       [-1.97752092,  1.13613714,  0.18252379, -0.38716746,  0.1540469 ]])

In [11]:
# Fusión condicional
np.where(array1 < array2, array1, array2)

array([[ 0.77185237,  0.19639932,  0.37070766,  0.19735883, -0.51541124],
       [-1.33404705,  0.84328705, -1.85125891, -0.74515301, -0.08960301],
       [-0.20238562, -0.92818649, -0.2794793 , -1.05604296, -1.10622212],
       [-1.55343445, -1.86590035,  0.49233096,  0.05255646,  1.23983636],
       [-1.97752092,  0.06281218,  0.18252379, -0.38716746, -1.52952003]])

In [12]:
# Anidación de condiciones
np.where(array1 < array2, np.where(array1 < 0, 0, array1), array2)

array([[ 0.77185237,  0.19639932,  0.37070766,  0.19735883, -0.51541124],
       [-1.33404705,  0.84328705, -1.85125891,  0.        ,  0.        ],
       [-0.20238562, -0.92818649,  0.        , -1.05604296, -1.10622212],
       [ 0.        , -1.86590035,  0.49233096,  0.05255646,  1.23983636],
       [-1.97752092,  0.06281218,  0.18252379, -0.38716746,  0.        ]])

### Funciones matemáticas y estadísticas

NumPy ofrece un amplio conjunto de funciones matemáticas y estadísticas que se pueden aplicar sobre ndarrays. A continuación se pueden encontrar los ejemplos más típicos (hay algunas más que pueden consultarse en la documentación oficial de NumPy).<br/>
<ul>
<li><b>sum:</b> Suma de elementos.</li>
<li><b>mean:</b> Media aritmética de los elementos.</li>
<li><b>median:</b> Mediana de los elementos.</li>
<li><b>std:</b> Desviación estándar de los elementos.</li>
<li><b>var:</b> Varianza de los elementos.</li>
<li><b>min:</b> Valor mínimo de los elementos.</li>
<li><b>max:</b> Valor máximo de los elementos.</li>
<li><b>argmin:</b> Índice del valor mínimo.</li>
<li><b>argmax:</b> Índice del valor máximo.</li>
<li><b>cumsum:</b> Suma acumulada de los elementos.</li>
<li><b>cumprod:</b> Producto acumulado de los elementos.</li>
</ul>

Todas estas funciones pueden recibir, además del ndarray sobre el que se aplicarán, un segundo parámetro llamado <b>axis</b>. Si no se recibe este parámetro las funciones se aplicarán sobre el conjunto global de los elementos del ndarray, pero si se incluye, podrá tomar dos valores:
<ul>
<li>Valor 0: Aplicará la función por columnas</li>
<li>Valor 1: Aplicará la función por filas</li>

In [13]:
array = np.random.randn(5, 4)
array

array([[ 6.84878478e-02,  9.04502602e-02, -7.70011890e-01,
         2.66957658e-01],
       [ 4.72521232e-01, -6.70714894e-01, -1.90060453e-01,
        -1.92321510e+00],
       [ 1.01708187e+00,  1.94129240e+00, -8.70657502e-04,
         1.55477500e+00],
       [-1.21024348e+00, -3.10567592e-01,  8.74807239e-01,
        -1.72070434e-01],
       [ 5.86912852e-01,  9.95957748e-01,  5.90892232e-01,
         4.53410678e-02]])

In [14]:
# Operación global
np.sum(array)

3.2577228918692165

In [15]:
# Operación a lo largo de las filas
np.sum(array, axis=0)

array([ 0.93476031,  2.04641792,  0.50475647, -0.22821181])

In [16]:
# Operación a lo largo de las columnas
np.sum(array, axis=1)

array([-0.34411612, -2.31146922,  4.51227861, -0.81807427,  2.2191039 ])

Adicionalmente algunas de estas funciones pueden ser utilizadas como "métodos" de los ndarray y no sólo como funciones sobre los mismos. En este caso la sintáxis cambiará y se utilizará la notación "ndarray.funcion()" 

In [17]:
array.sum()

3.2577228918692165

### Operaciones sobre ndarrays booleanos

Dado que, internamente, Python trata los valores booleanos True como 1 y los False como 0, es muy sencillo realizar operaciones matemáticas sobre estos valores booleanos de forma que se puedan hacer diferentes chequeos. Por ejemplo...

In [18]:
array = np.random.randn(5, 5)
array

array([[-1.32547527,  0.3716039 ,  0.59691406, -0.75987636,  0.55335693],
       [-1.56427351,  0.24728161,  0.99366875, -1.20804904,  0.69312869],
       [ 1.24639983,  0.49045217,  1.96554671,  0.38522788, -0.24969672],
       [-0.29276436,  1.95687744,  0.20420815,  0.39752038, -0.30632837],
       [-0.46403802,  0.13903103, -2.11202602,  1.1730888 , -0.26094981]])

In [19]:
array > 0

array([[False,  True,  True, False,  True],
       [False,  True,  True, False,  True],
       [ True,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False,  True, False,  True, False]])

In [20]:
# Elementos mayores que 0
(array > 0).sum()

15

In [21]:
#proporciones
(array > 0).mean()

0.6

In [22]:
# Elementos menores que la media
(array < array.mean()).sum()

10

NumPy también pone a nuestra disposición dos funciones de chequeo predefinidas sobre ndarrays booleanos:<br/>
<ul>
<li><b>any:</b> Para comprobar si alguno de los elementos es True.</li>
<li><b>all:</b> Para comprobar si todos los elementos son True.</li>
</ul>

In [23]:
# Alguno de los elementos cumple la condición
(array == 0).any()

False

In [24]:
# Todos los elementos cumplen la condición
((array >= -3) & (array <= 3)).all()

True

### Ordenación de ndarrays

In [25]:
array = np.random.randn(5, 5)
array

array([[ 0.29596266, -1.26847011,  0.02693391, -1.00503618, -1.29571781],
       [ 0.13969092, -1.45974699,  0.63504825, -1.5610027 ,  0.98984891],
       [ 0.63231123,  0.61724422, -1.20261385,  1.27231833, -0.26331387],
       [-0.5249368 , -1.17887542, -0.97147439,  1.8640574 ,  0.56953689],
       [-0.17323177, -0.13808309, -0.1498655 ,  0.19361929, -0.34174158]])

In [26]:
# Datos ordenados
np.sort(array)

array([[-1.29571781, -1.26847011, -1.00503618,  0.02693391,  0.29596266],
       [-1.5610027 , -1.45974699,  0.13969092,  0.63504825,  0.98984891],
       [-1.20261385, -0.26331387,  0.61724422,  0.63231123,  1.27231833],
       [-1.17887542, -0.97147439, -0.5249368 ,  0.56953689,  1.8640574 ],
       [-0.34174158, -0.17323177, -0.1498655 , -0.13808309,  0.19361929]])

In [27]:
# Datos ordenados según el primer eje
np.sort(array, axis=0)

array([[-0.5249368 , -1.45974699, -1.20261385, -1.5610027 , -1.29571781],
       [-0.17323177, -1.26847011, -0.97147439, -1.00503618, -0.34174158],
       [ 0.13969092, -1.17887542, -0.1498655 ,  0.19361929, -0.26331387],
       [ 0.29596266, -0.13808309,  0.02693391,  1.27231833,  0.56953689],
       [ 0.63231123,  0.61724422,  0.63504825,  1.8640574 ,  0.98984891]])

### Funciones de conjunto

NumPy permite realizar tratamientos sobre un ndarray asumiendo que el total de los elementos del mismo forman un conjunto.<br/>
<ul>
<li><b>unique:</b> Calcula el conjunto único de elementos sin duplicados.</li>
<li><b>intersect1d:</b> Calcula la intersección de los elementos de dos arrays.</li>
<li><b>union1d:</b> Calcula la unión de los elementos de dos arays.</li>
<li><b>in1d:</b> Calcula un array booleano que indica si cada elemento del primer array está contenido en el segundo.</li>
<li><b>setdiff1d:</b> Calcula la diferencia entre ambos conjuntos.</li>
<li><b>setxor1d:</b> Calcula la diferencia simétrica entre ambos conjuntos.</li>
</ul>

In [28]:
array1 = np.array([6, 0, 0, 0, 3, 2, 5, 6])
array1

array([6, 0, 0, 0, 3, 2, 5, 6])

In [29]:
array2 = np.array([7, 4, 3, 1, 2, 6, 5])
array2

array([7, 4, 3, 1, 2, 6, 5])

In [30]:
np.unique(array1)

array([0, 2, 3, 5, 6])

In [31]:
np.union1d(array1, array2)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
np.in1d(array1, array2)

array([ True, False, False, False,  True,  True,  True,  True])

In [36]:
np.setdiff1d(array1, array2)

array([0])