# Entrada y salida de ficheros

NumPy nos permite leer y escribir ficheros a disco tanto en formato binario (óptimo en términos de almacenamiento pero de dificil consumo fuera de NumPy) o formato texto (menos óptimo en términos de almacenamiento pero tratables desde cualquier otro módulo o tecnología).

In [1]:
import numpy as np

### Formato binario

Las dos funciones que permiten que NumPy trabaje con ficheros en formato binario son:
<ul>
<li><b>save:</b> Almacena un ndarray en un fichero en formato binario. Los ficheros tienen extensión .npy, si no se indica, se le asignará automáticamente.</li>
<li><b>load:</b> Carga un ndarray con los contenidos de un fichero en formato binario.</li>
</ul>

Obviamente, la carga de ficheros podrá hacerse únicamente desde ficheros binarios generados por NumPy.

In [2]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Guardado en el fichero array1.npy
np.save('array1', array)

In [6]:
# Carga del array desde el fichero creado
array2 = np.load('array1.npy')
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Formato texto

Las dos funciones que permiten que NumPy trabaje con ficheros en formato texto son:
<ul>
<li><b>savetxt:</b> Salva el contenido del ndarray en un fichero de texto con separador (por defecto la ",").</li>
<li><b>loadtxt:</b> Carga el contenido de un fichero de texto con separador (por defecto la ",") en un ndarray.</li>
</ul>

Aunque viable, es raro que un fichero de datos "común" contenga únicamente valores numéricos, lo que hace poco probable la utilización de esta función para la carga de ficheros de terceros.

In [7]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# Guardado en el fichero de texto array1.txt
np.savetxt('array1.txt', array, delimiter=',')

In [9]:
# Carga del array desde el fichero creado
array2 = np.loadtxt('array1.txt', delimiter=',')
array2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])