# NumPy - Ejercicios

### 1. Crea una función que reciba como parámetro un número n y devuelva una matriz cuadrada (dos dimensiones) de nxn donde los elementos de la matriz principal valgan 1 y el resto valgan n.

In [4]:
import numpy as np
def func_1(n):
    matriz = np.identity(n)
    matriz[matriz == 0] = n
    return matriz
func_1(5)

array([[1., 5., 5., 5., 5.],
       [5., 1., 5., 5., 5.],
       [5., 5., 1., 5., 5.],
       [5., 5., 5., 1., 5.],
       [5., 5., 5., 5., 1.]])

### 2. Crea una función que reciba dos números n y m que definirán ancho y alto de una matriz de nxm elementos numéricos secuenciales y un booleano que definirá si se debe devolver la matriz generada (False) o su traspuesta (True).

In [48]:
def func_2(n, m, generada):
    matriz = np.arange(n*m).reshape((n, m))
    if generada:
        return matriz
    return matriz.T
func_2(2,4, False)

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

### 3. Crea una función que genere un esquema de tablero de ajedrez (con valores 1 y 0, enteros) en base a dos parámetros: la dimensión (cuadrada) del tablero n y un flag que indique si el primer elemento de la primera fila debe ser un 1 (True) o un 0 (False).

In [57]:
def func_3(n, uno_primero):
    matriz = np.zeros(n*n).reshape(n, n)
    if uno_primero:
        matriz[1::2, 1::2] = 1
        matriz[::2, ::2] = 1
    else:
        matriz[::2, 1::2] = 1
        matriz[1::2, ::2] = 1
    return matriz
func_3(6, False)

array([[0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.]])

### 4. Crea una función que reciba dos arrays y genere un array que tenga 0 en todos los elementos y 1 en aquellos elementos del primer array que sean mayores que su equivalente del segundo array.

In [2]:
def func_4(arr1, arr2):
    final = np.zeros_like(arr1)
    final[arr1 > arr2] = 1
    return final
    
    

### 5. Crea una función que reciba un array y una tupla de enteros y devuelva la matriz resultante de seleccionar los índices de la tupla aplicados desde el final.

### 6. Replica la función del ejercicio 4 utilizando la función np.where

In [31]:
def func_6(arr1, arr2):
    final = np.where(arr1 > arr2, 1, 0)
    return final
arr1 = np.arange(15).reshape(3,5)
arr2 = np.arange(15, 30).reshape(3,5)
func_6(arr1, arr2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### 7. Crea una función que reciba una matriz y chequee si hay o no algún valor negativo en la misma.

In [13]:
def func_7(matriz):
    return (matriz < 0).any()
arr1 = np.arange(15).reshape(3,5)
func_7(arr1)

False

### 8. Crea una función que utilizando la del ejercicio anterior, sume el valor absoluto de todos los elementos negativos de una matriz recibida como parámetro o devuelve "No hay negativos" en caso de que no los haya.

In [32]:
def func_8(matriz):
    if not func_7(matriz):
        return "No hay negativos"
    return abs(np.sum(matriz[matriz<0]))
arr1 = np.arange(-7, 8).reshape(3,5)
func_8(arr1)

28

### 9. Crea una función que reciba una matriz unidimensional con nombres, una matriz con el mismo ancho que la matriz de nombres que contenga valores numéricos y un nombre de los de la primera lista. Deberá devolver, en una tupla, los descriptivos (mínimo, máximo, media, mediana y desviación típica) del vector de valores "asociado" al nombre seleccionado por posición. Ten en cuenta que el nombre introducido puede no estar en el listado y contrólalo.

In [30]:
def func_9(nombres, valores, nombre):
    return
    
nombres = ['A','B','C','D']
valores = np.arange(12).reshape((3, 4))
nombre = 'B'
#func_9(nombres, valores, nombre)
valores[nombres == nombre]

array([], shape=(0, 3, 4), dtype=int32)

### 10. Crea una función que reciba dos matrices y devuelva la secuencia ordenada de la union de los elementos únicos de ambas.

### 11. Crea una función que reciba un número n, genere una matriz nxn a partir de una secuencia numérica y escriba la misma en un fichero cuyo nombre se recibirá también como parámetro. Hazlo con ficheros binarios.

### 12. Crea una función que reciba el nombre de un fichero binario de NumPy, lo lea como binario, sume el contenido del mismo por filas y guarde el resultado en un fichero de texto con el mismo nombre (pero extensión txt).

### 13. Crea una función que reciba dos enteros n y m, genere dos matrices aleatorias (normales 0,1) de dimensiones nxm y mxn y haga el producto escalar de ambas para obtener una matriz nxn. Deberá devolver una tupla con las tres matrices.

### 14. Crea una función que reciba una matriz de datos y un entero n y devuelva una muestra (muestreo aleatorio simple) de n elementos.